export const FETCH_RECIPE = "FETCH_RECIPE";
export const FETCH_RECIPE_SUCCESS = "FETCH_RECIPE_SUCCESS";
export const FETCH_RECIPE_FAILURE = "FETCH_RECIPE_FAILURE";

export const UPDATE_SEARCH_ITEM = "UPDATE_SEARCH_ITEM";